import { $ } from "bun";
import { store } from "../server/store.ts";
import { createPullRequest, DEFAULT_FORGE } from "./forge.ts";
import type { ForgeConfig } from "../core/schemas.ts";
import type {
  PipelineRun,
  PanelResult,
  JudgePlan,
  ValidatorReport,
  HILResponse,
} from "../core/types.ts";

// ─── Create PR ────────────────────────────────────────────────────────────────

export async function createPR(
  repoPath: string,
  implWorktreePath: string,
  run: PipelineRun,
  forge: ForgeConfig = DEFAULT_FORGE
): Promise<string> {
  const { panelResults, judgePlan, validatorReport, hilResponse } = run;
  if (!panelResults || !judgePlan || !validatorReport || !hilResponse) {
    throw new Error("Missing pipeline data for PR creation");
  }

  const implBranch = await getImplBranch(implWorktreePath);
  const title = generatePRTitle(judgePlan);
  const body  = generatePRBody(run.id, panelResults, judgePlan, validatorReport, hilResponse);
  const remote = forge.remote ?? "origin";

  // Push the implementation branch to the configured remote.
  const pushed = await $`git -C ${implWorktreePath} push ${remote} ${implBranch}`.nothrow();
  if (pushed.exitCode !== 0) {
    store.log("warn", `Could not push ${implBranch} to '${remote}': ${pushed.stderr.toString().trim()}`);
    return manualFallback(run.id, implBranch, run.branch, title, body, `push failed: ${pushed.stderr.toString().trim().slice(0,200)}`);
  }

  // Create the PR/MR via the configured forge (CLI if present, else REST API).
  const result = await createPullRequest({ repoPath, config: forge }, {
    title, body, head: implBranch, base: run.branch,
  });

  if (result.url) {
    store.log("info", `PR/MR created via ${result.via} (${forge.provider}).`);
    return result.url;
  }

  store.log("warn", `Automatic PR creation skipped (${forge.provider}): ${result.detail ?? "unknown"}`);
  return manualFallback(run.id, implBranch, run.branch, title, body, result.detail);
}

async function manualFallback(
  runId: string,
  implBranch: string,
  baseBranch: string,
  title: string,
  body: string,
  reason?: string
): Promise<string> {
  const bodyPath = `/tmp/council-pr-${runId}.md`;
  await Bun.write(bodyPath, body);
  console.log(`\n📄 PR body written to: ${bodyPath}`);
  if (reason) console.log(`   (automatic creation unavailable: ${reason})`);
  console.log(`\nTo create the PR/MR manually:`);
  console.log(`  Branch: ${implBranch} → ${baseBranch}`);
  console.log(`  Title:  ${title}`);
  return `manual:${implBranch}`;
}

// ─── PR Content ───────────────────────────────────────────────────────────────

function generatePRTitle(plan: JudgePlan): string {
  const p0Count = plan.tasks.filter((t) => t.priority === "P0").length;
  const prefix = p0Count > 0 ? `[P0] ` : "";
  const firstSentence = plan.summary.split(".")[0] ?? plan.summary;
  return `${prefix}Council: ${firstSentence.slice(0, 60)}`;
}

function generatePRBody(
  runId: string,
  panelResults: PanelResult[],
  plan: JudgePlan,
  validator: ValidatorReport,
  hil: HILResponse
): string {
  const timestamp = new Date().toISOString();

  const panelSection = panelResults.map((r) =>
    `**${r.label}** \`[${r.riskLevel.toUpperCase()}]\`\n` +
    r.keyFindings.slice(0, 3).map((f) => `- ${f}`).join("\n")
  ).join("\n\n");

  const tasksSection = plan.tasks.map((t) =>
    `- \`[${t.priority}]\` **${t.id}**: \`${t.action} ${t.file}\`\n` +
    `  > ${t.instruction.slice(0, 100)}\n` +
    `  > *Source: ${t.source.join(", ")}*`
  ).join("\n\n");

  const riskSection = plan.riskFlags.length > 0
    ? `\n### 🚨 Risk Flags\n${plan.riskFlags.map((f) => `- ${f}`).join("\n")}\n`
    : "";

  const outOfScopeSection = plan.outOfScope.length > 0
    ? `\n### 🚫 Out of Scope (this cycle)\n${plan.outOfScope.map((s) => `- ${s}`).join("\n")}\n`
    : "";

  const hilNotesSection = hil.notes
    ? `\n**Reviewer notes:** ${hil.notes}\n`
    : "";

  return `## 🤖 Perspective Council Report
> Run ID: \`${runId}\` · ${timestamp}

---

## 📋 Panel Summary

${panelSection}

---

## 📐 Judge's Implementation Plan

${plan.summary}

${tasksSection}
${riskSection}${outOfScopeSection}

---

## ✅ Validator Report

**Verdict:** \`${validator.verdict}\`

${validator.notes}

---

## 👤 Human Review

**Approved by:** @${hil.reviewer}
**Decision:** \`${hil.decision}\`
${hilNotesSection}

---

*Generated by Perspective Council · Claude Code Implementor · Bun Orchestrator*`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function getImplBranch(worktreePath: string): Promise<string> {
  const result = await $`git -C ${worktreePath} branch --show-current`.text();
  return result.trim();
}
