import { $ } from "bun";
import type {
  PipelineRun,
  PanelResult,
  JudgePlan,
  ValidatorReport,
  HILResponse,
} from "../core/types.ts";

// ─── Create PR ────────────────────────────────────────────────────────────────

export async function createPR(
  repoPath: string,
  implWorktreePath: string,
  run: PipelineRun
): Promise<string> {
  const { panelResults, judgePlan, validatorReport, hilResponse } = run;
  if (!panelResults || !judgePlan || !validatorReport || !hilResponse) {
    throw new Error("Missing pipeline data for PR creation");
  }

  // Push the implementation branch
  const implBranch = await getImplBranch(implWorktreePath);
  await $`git -C ${implWorktreePath} push origin ${implBranch}`.quiet();

  const title = generatePRTitle(judgePlan);
  const body  = generatePRBody(run.id, panelResults, judgePlan, validatorReport, hilResponse);

  // Use GitHub CLI if available, otherwise print instructions
  const ghAvailable = await checkGHCLI();

  if (ghAvailable) {
    const result = await $`gh pr create \
      --repo ${repoPath} \
      --base ${run.branch} \
      --head ${implBranch} \
      --title ${title} \
      --body ${body}`.text();
    return result.trim();
  } else {
    // Write PR body to file so user can paste it
    const bodyPath = `/tmp/council-pr-${run.id}.md`;
    await Bun.write(bodyPath, body);
    console.log(`\n📄 PR body written to: ${bodyPath}`);
    console.log(`\nTo create the PR manually:`);
    console.log(`  Branch: ${implBranch} → ${run.branch}`);
    console.log(`  Title: ${title}`);
    return `manual:${implBranch}`;
  }
}

// ─── PR Content ───────────────────────────────────────────────────────────────

function generatePRTitle(plan: JudgePlan): string {
  const p0Count = plan.tasks.filter((t) => t.priority === "P0").length;
  const prefix = p0Count > 0 ? `[P0] ` : "";
  const firstSentence = plan.summary.split(".")[0] ?? plan.summary;
  return `${prefix}Council: ${firstSentence.slice(0, 60)}`;
}

function generatePRBody(
  runId: string,
  panelResults: PanelResult[],
  plan: JudgePlan,
  validator: ValidatorReport,
  hil: HILResponse
): string {
  const timestamp = new Date().toISOString();

  const panelSection = panelResults.map((r) =>
    `**${r.label}** \`[${r.riskLevel.toUpperCase()}]\`\n` +
    r.keyFindings.slice(0, 3).map((f) => `- ${f}`).join("\n")
  ).join("\n\n");

  const tasksSection = plan.tasks.map((t) =>
    `- \`[${t.priority}]\` **${t.id}**: \`${t.action} ${t.file}\`\n` +
    `  > ${t.instruction.slice(0, 100)}\n` +
    `  > *Source: ${t.source.join(", ")}*`
  ).join("\n\n");

  const riskSection = plan.riskFlags.length > 0
    ? `\n### 🚨 Risk Flags\n${plan.riskFlags.map((f) => `- ${f}`).join("\n")}\n`
    : "";

  const outOfScopeSection = plan.outOfScope.length > 0
    ? `\n### 🚫 Out of Scope (this cycle)\n${plan.outOfScope.map((s) => `- ${s}`).join("\n")}\n`
    : "";

  const hilNotesSection = hil.notes
    ? `\n**Reviewer notes:** ${hil.notes}\n`
    : "";

  return `## 🤖 Perspective Council Report
> Run ID: \`${runId}\` · ${timestamp}

---

## 📋 Panel Summary

${panelSection}

---

## 📐 Judge's Implementation Plan

${plan.summary}

${tasksSection}
${riskSection}${outOfScopeSection}

---

## ✅ Validator Report

**Verdict:** \`${validator.verdict}\`

${validator.notes}

---

## 👤 Human Review

**Approved by:** @${hil.reviewer}
**Decision:** \`${hil.decision}\`
${hilNotesSection}

---

*Generated by Perspective Council · Claude Code Implementor · Bun Orchestrator*`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function getImplBranch(worktreePath: string): Promise<string> {
  const result = await $`git -C ${worktreePath} branch --show-current`.text();
  return result.trim();
}

async function checkGHCLI(): Promise<boolean> {
  try {
    await $`gh --version`.quiet();
    return true;
  } catch {
    return false;
  }
}
